//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardGames.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoardGames.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chesspiece, from position, to position Example N B1 C3 (P: pawn,  N: knight, B: bishop, R: rook, Q: queen, K: king)..
        /// </summary>
        public static string chess_command_instructions {
            get {
                return ResourceManager.GetString("chess_command_instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give command to move chess piece..
        /// </summary>
        public static string chess_give_command {
            get {
                return ResourceManager.GetString("chess_give_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check!.
        /// </summary>
        public static string chess_movement_check {
            get {
                return ResourceManager.GetString("chess_movement_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkmate!.
        /// </summary>
        public static string chess_movement_checkmate {
            get {
                return ResourceManager.GetString("chess_movement_checkmate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That movement is invalid as it would trigger check for your king..
        /// </summary>
        public static string chess_movement_invalid_check {
            get {
                return ResourceManager.GetString("chess_movement_invalid_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a new Chess piece (P: pawn,  N: knight, B: bishop, R: rook, Q: queen, K: king)..
        /// </summary>
        public static string chess_new_piece {
            get {
                return ResourceManager.GetString("chess_new_piece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can and must jump and capture with a piece of yours..
        /// </summary>
        public static string draughts_do_turn_jump {
            get {
                return ResourceManager.GetString("draughts_do_turn_jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have captured all the enemy pieces!.
        /// </summary>
        public static string draughts_end_enemy_killed {
            get {
                return ResourceManager.GetString("draughts_end_enemy_killed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a draughts game. There are simple figures (Man - M) which can be promoted to powerful ones (King - K). You may move a piece by defining the starting and ending position. If you would jump multiple times, then you have to add these commands one after another. Command example: D3 F5 or D3 F5 -enter- F5 D7..
        /// </summary>
        public static string draughts_instructions {
            get {
                return ResourceManager.GetString("draughts_instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Man piece has been promoted to King!.
        /// </summary>
        public static string draughts_piece_promote {
            get {
                return ResourceManager.GetString("draughts_piece_promote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some commands you may execute here. &apos;none&apos;, &apos;quit&apos;, &apos;exit&apos; aborts the game creation..
        /// </summary>
        public static string factory_commands {
            get {
                return ResourceManager.GetString("factory_commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have terminated the game menu..
        /// </summary>
        public static string factory_exit {
            get {
                return ResourceManager.GetString("factory_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to play the game locally or on the network?.
        /// </summary>
        public static string factory_local_or_network {
            get {
                return ResourceManager.GetString("factory_local_or_network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game cannot be started..
        /// </summary>
        public static string game_cannot_start {
            get {
                return ResourceManager.GetString("game_cannot_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What game would you like to play?.
        /// </summary>
        public static string game_choose {
            get {
                return ResourceManager.GetString("game_choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some commands you may execute during game. These are the following: &apos;quit&apos;, &apos;exit&apos;..
        /// </summary>
        public static string game_commands {
            get {
                return ResourceManager.GetString("game_commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have aborted the currently running game..
        /// </summary>
        public static string game_exit {
            get {
                return ResourceManager.GetString("game_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game has ended..
        /// </summary>
        public static string game_has_ended {
            get {
                return ResourceManager.GetString("game_has_ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game has started..
        /// </summary>
        public static string game_has_started {
            get {
                return ResourceManager.GetString("game_has_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That is not a valid position on the table..
        /// </summary>
        public static string game_invalid_table_position {
            get {
                return ResourceManager.GetString("game_invalid_table_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game is loading..
        /// </summary>
        public static string game_is_starting {
            get {
                return ResourceManager.GetString("game_is_starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game can be played only by {0} player(s)..
        /// </summary>
        public static string game_player_numbers {
            get {
                return ResourceManager.GetString("game_player_numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current games are available: {0}..
        /// </summary>
        public static string games_list {
            get {
                return ResourceManager.GetString("games_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected &apos;from&apos; cell is empty..
        /// </summary>
        public static string input_cell_from_empty {
            get {
                return ResourceManager.GetString("input_cell_from_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected &apos;from&apos; piece is not yours..
        /// </summary>
        public static string input_cell_wrong_owner {
            get {
                return ResourceManager.GetString("input_cell_wrong_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected &apos;from&apos; piece is something different: {0}..
        /// </summary>
        public static string input_cell_wrong_piece_type {
            get {
                return ResourceManager.GetString("input_cell_wrong_piece_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input has invalid parameter(s) {0}..
        /// </summary>
        public static string input_invalid_parameters {
            get {
                return ResourceManager.GetString("input_invalid_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input has missing parameter(s)..
        /// </summary>
        public static string input_missing_parameters {
            get {
                return ResourceManager.GetString("input_missing_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not enough input parameters (piece from to)..
        /// </summary>
        public static string input_not_enough_parameters {
            get {
                return ResourceManager.GetString("input_not_enough_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have lost the game. :(.
        /// </summary>
        public static string player_defeated {
            get {
                return ResourceManager.GetString("player_defeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enemy turn to move..
        /// </summary>
        public static string player_enemyturn {
            get {
                return ResourceManager.GetString("player_enemyturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} wins the game!.
        /// </summary>
        public static string player_game_win {
            get {
                return ResourceManager.GetString("player_game_win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a name for {0} player..
        /// </summary>
        public static string player_give_name {
            get {
                return ResourceManager.GetString("player_give_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s turn to move..
        /// </summary>
        public static string player_turn {
            get {
                return ResourceManager.GetString("player_turn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won the game! ^^.
        /// </summary>
        public static string player_victory {
            get {
                return ResourceManager.GetString("player_victory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your turn to move..
        /// </summary>
        public static string player_yourturn {
            get {
                return ResourceManager.GetString("player_yourturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong position, it does not exist..
        /// </summary>
        public static string wrong_position_does_not_exist {
            get {
                return ResourceManager.GetString("wrong_position_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong position, you cannot do that..
        /// </summary>
        public static string wrong_position_invalid {
            get {
                return ResourceManager.GetString("wrong_position_invalid", resourceCulture);
            }
        }
    }
}
